In [4]:
import numpy as np

In [3]:
def function1():print("china")
def function1():print("pakistan")
function1()


pakistan


In [30]:

l1=(1,2,3)
print(sum(l1))
print(np.sum(l1))


6
6


In [33]:

l1=np.arange(1,30000)
l1+5


array([    6,     7,     8, ..., 30002, 30003, 30004])

In [38]:

function1=np.arange(1,13)
print(function1)
print('deminsion',l1.ndim)
print('datatype',function1.dtype)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
deminsion 1
datatype int32


In [12]:

function1=np.arange(1,13).reshape((6,-1))
print (function1)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [13]:

function2 = np.arange(10,37,dtype=np.float).reshape((3,3,3))
print(function2)


[[[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]

 [[28. 29. 30.]
  [31. 32. 33.]
  [34. 35. 36.]]]


In [20]:

    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1,1000+1).reshape((10,100))
    print(a)
    print(a[(a % 5==0)&(a%7==0)])
     #wrtie your code here
    

[[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
    15   16   17   18   19   20   21   22   23   24   25   26   27   28
    29   30   31   32   33   34   35   36   37   38   39   40   41   42
    43   44   45   46   47   48   49   50   51   52   53   54   55   56
    57   58   59   60   61   62   63   64   65   66   67   68   69   70
    71   72   73   74   75   76   77   78   79   80   81   82   83   84
    85   86   87   88   89   90   91   92   93   94   95   96   97   98
    99  100]
 [ 101  102  103  104  105  106  107  108  109  110  111  112  113  114
   115  116  117  118  119  120  121  122  123  124  125  126  127  128
   129  130  131  132  133  134  135  136  137  138  139  140  141  142
   143  144  145  146  147  148  149  150  151  152  153  154  155  156
   157  158  159  160  161  162  163  164  165  166  167  168  169  170
   171  172  173  174  175  176  177  178  179  180  181  182  183  184
   185  186  187  188  189  190  191  192  193  194

In [11]:
#task4

    #Swap columns 1 and 2 in the array arr.
   
arr = np.arange(9).reshape(3,3)
print("array before swaping")
print(arr)
arr[:,[0,1]]=arr[:,[1,0]]
print("\nafter swaping array:")  
print(arr)
   # """Expected Output:
         # array([[1, 0, 2],
               # [4, 3, 5],
               # [7, 6, 8]])
                

array before swaping
[[0 1 2]
 [3 4 5]
 [6 7 8]]

after swaping array:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [23]:
z=np.arange(1,21)
print(z)
z=np.zeros((4,5))
z

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
#task6

    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively
   
arr =np.zeros(10) #wrtie your code here
  
print(arr)
print("\nfifth and eighth value which is 10,20\n")
arr[5] = 10
arr[8]=20
print(arr)
   

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

fifth and eighth value which is 10,20

[ 0.  0.  0.  0.  0. 10.  0.  0. 20.  0.]


In [45]:
#task7

    #  Create an array of zeros with the same shape and type as X. Dont use reshape method

x = np.zeros(4, dtype=np.int64)

print(x)
x.dtype
   


[0 0 0 0]


dtype('int64')

In [26]:
# Create a new array of 2x5 uints, filled with 6.
x = np.full((2,6), 6)
x

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [29]:
#task9
    # Create an array of 2, 4, 6, 8, ..., 100.
     
a=np.arange(1,101)# write your code here
  
print(a)

a[(a%2==0)]


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
 #task10 abi rehta hy
arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
brr = np.array([1,2,3])
subt =brr-arr # write your code here 
  
print(subt)



[[-2 -1  0]
 [-3 -2 -1]
 [-4 -3 -2]]


In [8]:
#task11
#Replace all odd numbers in arr with -1 without changing arr.
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
np.where(arr%3==0, -1, arr)
#Expected Output:
              #array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

[0 1 2 3 4 5 6 7 8 9]


array([-1,  1,  2, -1,  4,  5, -1,  7,  8, -1])

In [36]:
#task 12
#def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
arr = np.arange(1,4)
b =arr.repeat(3) #write your code here
ans=np.hstack((b,arr,arr,arr))
print(ans)
  

#"""
#Expected Output:
#array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
#""" 

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [22]:
#task13
    # Set a condition which gets all items between 5 and 10 from arr.
    
    
arr = np.array([2, 6, 1, 9, 10, 3, 27])
arr
ans = arr[(arr > 5) & (arr < 10)]
ans
    #ans = #write your code here 
  
    #return ans

    # """
    # Expected Output:
            #  array([6, 9])

array([6, 9])

In [15]:
#task14

    # Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method
    
    
arr = np.arange(10, 34, 1) #write reshape code

arr=arr.reshape(8,3)
print(arr)

ans=np.split(arr, 4)
print("\nsplit 8x3 array into 4 sub array\n")
print(ans)
  
    #return ans

    # """
    # Expected Output:
    #   [array([[10, 11, 12],[13, 14, 15]]), 
    #    array([[16, 17, 18],[19, 20, 21]]), 
      #  array([[22, 23, 24],[25, 26, 27]]), 
    #    array([[28, 29, 30],[31, 32, 33]])]
 

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

split 8x3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [30]:
#task15
    #Sort following NumPy array by the second column
    
    
arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
ans = #write your code here 
  
return ans

     """
     Expected Output:
           array([[-4,  1,  7],
                   [ 8,  2, -2],
                   [ 6,  3,  9]])
     """ 

IndentationError: unexpected indent (<ipython-input-30-a77900f619f0>, line 5)

In [36]:
#task16

    #Write a NumPy program to join a sequence of arrays along depth.
    
    
x = np.array([[1], [2], [3]])
y = np.array([[2], [3], [4]])
x,y
arr = np.dstack((x,y))
print(arr)

    #ans = #write your code here 
  
    #return ans

    # Expected Output:
         #       [[[1 2]]

         #       [[2 3]]

         #       [[3 4]]]


[[[1 2]]

 [[2 3]]

 [[3 4]]]


In [44]:
#Task17

    # replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where
arr = np.arange(1,10*10+1).reshape((10,10))
print(arr)
ans=np.where(arr%3==0,"yes","no")
print("\nafter dividing array\n")
ans                                    # Write Your Code HERE

#Excpected Out

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

after dividing array



array([['no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no'],
       ['no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no'],
       ['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes'],
       ['no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no'],
       ['no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no'],
       ['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes'],
       ['no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no'],
       ['no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no'],
       ['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes'],
       ['no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no']],
      dtype='<U3')

In [3]:
#Task18

    # count values of "students" are exist in "piaic"
piaic = np.random.randint(1,100, size=30)
cnic = np.random.randint(1,10,size=3)
print(piaic, cnic,sep='\n\n')

    #Expected output: 3


[42 52 26 95 53 49 47  8 65 88 20 97 13 86 38 86 26 37 42  9 46  5 53 15
 45 17 43 71 18 70]

[1 2 3]


In [33]:
# Task19
#def function19():
  #Create variable "X" from 1,25 (both are included) range values
    #Convert "X" variable dimension into 5 rows and 5 columns
    #Create one more variable "W" copy of "X" 
    #Swap "W" row and column axis (like transpose)
    # then create variable "b" with value equal to 5
    # Now return output as "(X*W)+b:

X =np.arange(5*5).reshape((5,5))
X
W=X
print(X)
X.T
b=5
output=(X*W)+b
output


   # W =   # Write your code here 
    #b =   # Write your code here
    #output =    # Write your code here
    #return output
    #expected output
   # """
    #array([[  6,  17,  38,  69, 110],
     #  [ 17,  54, 101, 158, 225],
      # [ 38, 101, 174, 257, 350],
       #[ 69, 158, 257, 366, 485],
       #[110, 225, 350, 485, 630]])
    #"""


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  5,   6,   9,  14,  21],
       [ 30,  41,  54,  69,  86],
       [105, 126, 149, 174, 201],
       [230, 261, 294, 329, 366],
       [405, 446, 489, 534, 581]])

In [10]:
#Task20

    #apply fuction "abc" on each value of Array "X"
x = np.arange(1,11)
def abc(x):
return=(x*2+3-2)

return #Write your Code here
#Expected Output: array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

IndentationError: expected an indented block (<ipython-input-10-cf927d08702e>, line 6)